apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "trivy-no-network"
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchBinaries:
      - operator: "Postfix"
        values:
        - "/trivy"
      matchActions:
      - action: Sigkill
