apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "curl-localhost-only"
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchBinaries:
      - operator: "Postfix"
        values:
        - "/curl"
      matchArgs:
      - index: 0
        operator: "DAddr"
        values:
        - "127.0.0.1"
      - index: 0
        operator: "DPort"
        values:
        - "18080"
      matchActions:
      - action: NoPost
    - matchBinaries:
      - operator: "Postfix"
        values:
        - "/curl"
      matchActions:
      - action: Sigkill
