apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "sensitive-file"
spec:
  kprobes:
  - call: "security_file_permission"
    syscall: false
    return: true
    args:
    - index: 0
      type: "file"
    - index: 1
      type: "int"
    returnArg:
      index: 0
      type: "int"
    selectors:
    - matchBinaries:
      - operator: "Postfix"
        values:
        - "/sudo"
      matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/etc/shadow"
      - index: 1
        operator: "Equal"
        values:
        - "4"
      matchActions:
      - action: NoPost
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/etc/shadow"
        - "/root/.ssh"
      - index: 1
        operator: "Equal"
        values:
        - "4"
      matchActions:
      - action: Sigkill
